#!/usr/bin/env bash
# interactively pick one of the active mpv instances
# print the socket file path

set -e

declare -a ACTIVE
declare -a ACTIVE_OPTS
declare -a SELECT_OPTS
INTERACT=1

usage() {
    cat <<-EOF
usage: ${0##*/} [options]

options:
    -a, --ampv           Only include sockets ending in "ampv".
    -c, --current        Only consider currently playing instances.
    -f, --fzf            Use fzf for selection instead of dmenu.
    -F, --full           Show full details including media title.
    -h, --help           Show this help message and exit.
    -m, --music          Only include sockets ending in "music".
    -p, --pid            Print the PID instead of the socket path.
    -q, --quiet          Suppress error messages.
    -u, --umpv           Only include sockets ending in "umpv".
    -U, --unique         Only show unique mpv sockets (i.e. unnamed sockets).
EOF
    exit 0
}

abort() {
    [[ "$QUIET" -eq 1 ]] && return 0
    echo "$1" >&2
    return 1
}

get_opts() {
    while [[ "$#" -ne 0 ]]; do
        case "$1" in
            -a | --ampv) ACTIVE_OPTS+=("--ampv") ;;
            -c | --current) IS_PLAYING=1 ;;
            -f | --fzf) INTERACT=0 ;;
            -F | --full) FULL=1 ;;
            -h | --help) usage ;;
            -m | --music) ACTIVE_OPTS+=("--music") ;;
            -p | --pid) PID=1 ;;
            -q | --quiet) QUIET=1 ;;
            -u | --umpv) ACTIVE_OPTS+=("--umpv") ;;
            -U | --unique) ACTIVE_OPTS=("--unique") ;;
            --)
                shift
                SELECT_OPTS+=("$@")
                break
                ;;
            *)
                abort "Invalid option(s): $*"
                return 1
                ;;
        esac
        shift
    done

    # Set the command to use for getting sockets
    if [[ "$IS_PLAYING" -eq 1 ]]; then
        GET_COMMAND="mpv-currently-playing --socket"
    else
        GET_COMMAND="mpv-active-sockets"
    fi
}

get_sockets() {
    readarray -t ACTIVE < <($GET_COMMAND "${ACTIVE_OPTS[@]}")
}

print_sockets() {
    for SOCKET in "${ACTIVE[@]}"; do
        if [[ "$PID" -eq 1 ]]; then
            printf '%s:' "$(mpv-get-property "$SOCKET" 'pid')"
        else
            printf '%s:' "$SOCKET"
        fi
        mpv-get-property "$SOCKET" 'media-title' || exit $?
    done
}

print_active() {
    local chosen
    chosen="$(print_sockets)"

    if [[ "$FULL" -eq 1 ]]; then
        echo "$chosen"
    else
        echo "${chosen%%:*}"
    fi
    return 0
}

select_instance() {
    local chosen=""

    if [[ "$INTERACT" -eq 1 ]]; then
        # Use dmenu for selection
        chosen="$(print_sockets | dmenu -i -l 10 -p "Select:")" || {
            abort 'No instance selected...'
            return 1
        }
    else
        # Use fzf for selection
        chosen="$(print_sockets | fzf +m -i --prompt='Select mpv instance... > ')" || {
            abort 'No instance selected...'
            return 1
        }
    fi

    if [[ -n "$chosen" ]]; then
        if [[ "$FULL" -eq 1 ]]; then
            echo "$chosen"
        else
            echo "${chosen%%:*}"
        fi
    else
        abort "Error getting selected instance..."
        return 1
    fi
}

main() {
    get_opts "$@" || return 1
    get_sockets

    if [[ "${#ACTIVE[@]}" -eq 1 ]]; then
        print_active
    elif [[ "${#ACTIVE[@]}" -eq 0 ]]; then
        abort "No active mpv instances..."
        return 1
    else
        select_instance || return 1
    fi
}

main "$@"
